# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

default:
    resource: "@XaavWikiBundle/Controller"
    type:     annotation